# Generated by Django 3.1.6 on 2021-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20210206_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='module_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя модуля'),
        ),
    ]
