# Generated by Django 3.1.6 on 2021-02-06 21:32

from django.db import migrations, models
import plugins.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_plugins_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugins',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='plugins',
            name='zipfile',
            field=models.FileField(blank=True, upload_to=plugins.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
