# Generated by Django 3.1.6 on 2021-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_remove_plugins_apps_install_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Версия'),
        ),
    ]
