# Generated by Django 3.1.6 on 2021-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_auto_20210207_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='apps_install_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя APP INSTALL'),
        ),
    ]
