# Generated by Django 3.1.4 on 2021-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_plugins_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='related_class_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя класса для связи'),
        ),
    ]
